-- CreateTable
CREATE TABLE `students` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `full_name` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `campus` ENUM('ANTONIO_VARAS', 'VINA_DEL_MAR', 'CONCEPCION') NOT NULL,
    `career` ENUM('CIVIL_ENGINEERING', 'COMPUTER_ENGINEERING', 'ELECTRICAL_ENGINEERING', 'INDUSTRIAL_ENGINEERING') NOT NULL,
    `subject` ENUM('CALCULUS_I', 'LINEAR_ALGEBRA', 'PHYSICS', 'PROGRAMMING', 'ELECTRONICS') NOT NULL,
    `current_year` INTEGER NOT NULL,
    `language` ENUM('SPANISH', 'ENGLISH', 'SPANISH_ENGLISH') NOT NULL,
    `modality` ENUM('IN_PERSON', 'ONLINE') NOT NULL,
    `request` TEXT NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `students_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `mentors` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `full_name` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `campus` ENUM('ANTONIO_VARAS', 'VINA_DEL_MAR', 'CONCEPCION') NOT NULL,
    `career` ENUM('CIVIL_ENGINEERING', 'COMPUTER_ENGINEERING', 'ELECTRICAL_ENGINEERING', 'INDUSTRIAL_ENGINEERING') NOT NULL,
    `specialty_subject` ENUM('CALCULUS_I', 'LINEAR_ALGEBRA', 'PHYSICS', 'PROGRAMMING', 'ELECTRONICS') NOT NULL,
    `language` ENUM('SPANISH', 'ENGLISH', 'SPANISH_ENGLISH') NOT NULL,
    `modality` ENUM('IN_PERSON', 'ONLINE') NOT NULL,
    `bio` TEXT NOT NULL,
    `availability` TEXT NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `mentors_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
